# Label the master node to install portainer
#! > docker node update --label-add portainer.portainer-data=true $(docker info -f '{{.Swarm.NodeID}}')

x-default-opts: &default-opts
  logging:
    driver: "json-file"
    options:
      max-size: "10m"
      max-file: "3"

services:
  agent:
    <<: *default-opts
    image: portainer/agent:lts
    environment:
      # Use the node IP instead of DNS name
      AGENT_CLUSTER_ADDR: ${NODE_IP:-127.0.0.1}
      AGENT_PORT: 9001
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
    networks:
      - internal_network
    deploy:
      mode: global
      placement:
        constraints:
          - node.platform.os == linux
      resources:
        limits:
          cpus: "0.75"
          memory: 256M
        reservations:
          cpus: "0.1"
          memory: 128M
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s

  portainer:
    <<: *default-opts
    image: portainer/portainer-ce:lts
    command: ["-H", "tcp://agent:9001", "--tlsskipverify"]
    volumes:
      - 2-portainer_data:/data
    networks:
      - internal_network
      - proxy_internet_access_network
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
          - node.labels.portainer.portainer-data == true
      resources:
        limits:
          cpus: "1.0"
          memory: 512M
        reservations:
          cpus: "0.2"
          memory: 256M
      labels:
        - "traefik.enable=true"
        - "traefik.swarm.network=proxy_internet_access_network"
        - "traefik.http.services.portainer.loadbalancer.server.port=9000"
        - "traefik.http.services.portainer.loadbalancer.passhostheader=true"
        # HTTPS router:
        - "traefik.http.routers.portainer.rule=Host(`portainer.<metz-domain.com>`)"
        - "traefik.http.routers.portainer.entrypoints=websecure"
        - "traefik.http.routers.portainer.tls=true"
        - "traefik.http.routers.portainer.tls.certresolver=letsencryptresolver"
      update_config:
        parallelism: 1
        delay: 10s
        order: start-first
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s

networks:
  internal_network:
    driver: overlay
    attachable: true
    external: false
  proxy_internet_access_network:
    external: true

volumes:
  2-portainer_data:
    name: 2-portainer_data
    external: true
